### ISSUE TITLE
ipfshttpclient (python) connection error

### ISSUE THREAD

**Issue by kingofmidas** [ipfs-shipyard/py-ipfs-http-client#217]
**I have ipfshttpclient version 0.4.12 and ipfs demon version 0.4.23. Ipfs and python are in containers:**
```
 ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports: 
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    networks: 
      - knox-net

networks:
  knox-net:
    driver: bridge
```
**I try connect method:** `client = ipfshttpclient.connect("/dns/ipfs/tcp/5001")`
**but get error:**
(From postman)

> ConnectionError at /api/v1/upload
> ConnectionError: HTTPConnectionPool(host='ipfs', port=5001): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<ipfshttpclient.requests_wrapper.HTTPConnection object at 0x7f99ef67c4f0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> 
> Request Method: POST
> Request URL: http://127.0.0.1:8000/api/v1/upload
> Django Version: 3.0.6
> Python Executable: /usr/local/bin/python
> Python Version: 3.8.0
> Python Path: ['/app', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/site-packages']

(EDIT by @ntninja for readability:)
